on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
      build_params:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      export_name:
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      # Checkout Godot
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: "godotengine/godot"
          path: "godot"
          ref: ${{ inputs.godot_tag }}
      # Install the Vulkan SDK, script copied from the official Godot build scripts.
      - name: Install Vulkan SDK
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          # Download and install the Vulkan SDK.
          curl -L "https://sdk.lunarg.com/sdk/download/latest/mac/vulkan-sdk.dmg" -o /tmp/vulkan-sdk.dmg
          hdiutil attach /tmp/vulkan-sdk.dmg -mountpoint /Volumes/vulkan-sdk
          /Volumes/vulkan-sdk/InstallVulkan.app/Contents/MacOS/InstallVulkan \
              --accept-licenses --default-answer --confirm-command install
          cnt=5
          until hdiutil detach -force /Volumes/vulkan-sdk
          do
             [[ cnt -eq "0" ]] && break
             sleep 1
             ((cnt--))
          done
          rm -f /tmp/vulkan-sdk.dmg
          echo 'Vulkan SDK installed successfully!'
      - name: Install Build Tools
        run: |
          brew install scons yasm
      - name: Build MacOS
        working-directory: "godot"
        run: |
          scons ${{ inputs.build_params }}
      - name: Upload MacOS Build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: godot/bin/${{ inputs.export_name }}
          if-no-files-found: error
          retention-days: 1
      - name: Zip the MacOS Apps
        run: |
          pushd godot/misc/dist
          zip -r ./osx_tools.zip ./osx_tools.app/
          zip -r ./osx_template.zip ./osx_template.app/
          popd
      - name: Upload MacOS Tool App
        uses: actions/upload-artifact@v3
        with:
          name: macos-tool-app
          path: godot/misc/dist/osx_tools.zip
          if-no-files-found: error
          retention-days: 1
      - name: Upload MacOS Template App
        uses: actions/upload-artifact@v3
        with:
          name: macos-template-app
          path: godot/misc/dist/osx_template.zip
          if-no-files-found: error
          retention-days: 1
