name: Build Windows

on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
      godotsteam_tag:
        required: true
        type: string
      godotwasm_tag:
        required: true
        type: string
      steamworks_sdk_tag:
        required: true
        type: string
      binary_name:
        required: true
        type: string
      build_params:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      export_name:
        required: true
        type: string
    secrets:
      steamworks_sdk_repo:
        required: true
      steamworks_sdk_repo_token:
        required: true

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          path: godot
          ref: ${{ inputs.godot_tag }}

      - name: Checkout GodotSteam
        uses: actions/checkout@v3
        with:
          repository: Gramps/GodotSteam
          path: godotsteam
          ref: ${{ inputs.godotsteam_tag }}

      - name: Checkout Godot Wasm
        uses: actions/checkout@v3
        with:
          repository: ashtonmeuser/godot-wasm
          path: wasm
          ref: ${{ inputs.godotwasm_tag }}

      - name: Copy Modules
        run: |
          dir
          robocopy godotsteam godot/modules/godotsteam /e
          robocopy wasm godot/modules/wasm /e
          dir godot/modules/godotsteam
          dir godot/modules/wasm
          EXIT 0

      - name: Checkout Steamworks SDK
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.steamworks_sdk_repo }}
          path: steamworks
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}

      - name: Copy Steamworks SDK
        run: |
          robocopy steamworks/public/steam godot/modules/godotsteam/sdk/public/steam /e
          robocopy steamworks/redistributable_bin godot/modules/godotsteam/sdk/redistributable_bin /e
          cd godot/modules/godotsteam/sdk && dir
          EXIT 0

      - name: Install Build Requirements
        run: |
          python --version
          python -m pip install scons
          scons --version

      - name: Build Windows
        working-directory: godot
        run: |
          scons ${{ inputs.build_params }}
          cd bin && ren ${{ inputs.binary_name }} ${{ inputs.export_name }}

      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: godot/bin/${{ inputs.export_name }}
          retention-days: 1

      - name: Upload Windows Steam Library
        uses: actions/upload-artifact@v3
        with:
          name: win_steam_api_64
          path: godot/modules/godotsteam/sdk/redistributable_bin/win64/steam_api64.dll
          retention-days: 1
