name: Build Linux

on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
      godotsteam_tag:
        required: true
        type: string
      godotwasm_tag:
        required: true
        type: string
      steamworks_sdk_tag:
        required: true
        type: string
      binary_name:
        required: true
        type: string
      build_params:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      export_name:
        required: true
        type: string
    secrets:
      steamworks_sdk_repo:
        required: true
      steamworks_sdk_repo_token:
        required: true

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          path: godot
          ref: ${{ inputs.godot_tag }}

      - name: Checkout GodotSteam
        uses: actions/checkout@v3
        with:
          repository: Gramps/GodotSteam
          path: godotsteam
          ref: ${{ inputs.godotsteam_tag }}

      - name: Checkout Godot Wasm
        uses: actions/checkout@v3
        with:
          repository: ashtonmeuser/godot-wasm
          path: wasm
          ref: ${{ inputs.godotwasm_tag }}

      - name: Copy Modules
        run: |
          cp -r godotsteam godot/modules/godotsteam
          cp -r wasm godot/modules/wasm

      - name: Checkout Steamworks SDK
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.steamworks_sdk_repo }}
          path: steamworks
          token: ${{ secrets.steamworks_sdk_repo_token }}
          ref: ${{ inputs.steamworks_sdk_tag }}

      - name: Copy Steamworks SDK
        run: |
          mkdir godot/modules/godotsteam/sdk/public
          cp -r steamworks/public godot/modules/godotsteam/sdk
          cp -r steamworks/redistributable_bin godot/modules/godotsteam/sdk
          ls -la godot/modules/godotsteam/sdk

      - name: Install Build Requirements
        run: |
          sudo add-apt-repository ppa:kisak/kisak-mesa
          sudo apt-get update
          sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
              libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip \
              llvm libspeechd-dev speech-dispatcher fontconfig libfontconfig-dev
          sudo apt-get install -qq mesa-vulkan-drivers

      - name: Build Linux Editor
        working-directory: godot
        run: |
          scons ${{ inputs.build_params }}
          mv bin/${{ inputs.binary_name }} bin/${{ inputs.export_name }}
          ls -la bin

      - name: Upload Linux Build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: godot/bin/${{ inputs.export_name }}
          retention-days: 1

      - name: Upload Linux Steam Library
        uses: actions/upload-artifact@v3
        with:
          name: linux-libsteam-api-so
          path: godot/modules/godotsteam/sdk/redistributable_bin/linux64/libsteam_api.so
          retention-days: 1
