name: Build Linux

on:
  workflow_call:
    inputs:
      godot_tag:
        required: true
        type: string
      binary_name:
        required: true
        type: string
      build_params:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      export_name:
        required: true
        type: string

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          path: godot
          ref: ${{ inputs.godot_tag }}

      - name: Install Build Requirements
        run: |
          sudo add-apt-repository ppa:kisak/kisak-mesa
          sudo apt-get update
          sudo apt-get install build-essential scons pkg-config libx11-dev libxcursor-dev \
              libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev \
              libdbus-1-dev libudev-dev libxi-dev libxrandr-dev yasm xvfb wget unzip \
              llvm libspeechd-dev speech-dispatcher fontconfig libfontconfig-dev
          sudo apt-get install -qq mesa-vulkan-drivers

      - name: Build Linux Editor
        working-directory: godot
        run: |
          scons ${{ inputs.build_params }}
          mv bin/${{ inputs.binary_name }} bin/${{ inputs.export_name }}
          ls -la bin

      - name: Upload Linux Build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: godot/bin/${{ inputs.export_name }}
          retention-days: 1
